/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.EventoController;
import controller.InvitadoController;
import java.io.IOException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Evento;
import model.Invitado;

/**
 *
 * @author alvar
 */
public class FrmBuscarTarea extends javax.swing.JFrame {

    /**
     * Creates new form FrmBuscarTarea
     */
    private InvitadoController tareaController;
    private EventoController proyectoController; 
    public FrmBuscarTarea() {
        initComponents();
        tareaController= new InvitadoController();
        proyectoController = new EventoController();
        configurarTabla();
        cargarTareasEnTabla();
        cargarAutoresEnComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTareas = new javax.swing.JTable();
        cboProyecto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Proyecto");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnTodos.setText("Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        tblTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTareas);

        cboProyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(31, 31, 31)
                                .addComponent(btnTodos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(cboProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTodos)
                    .addComponent(btnBuscar))
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
        String proyecto = cboProyecto.getSelectedItem().toString();
        
         System.out.println("Proyecto seleccionado: " + proyecto);  // Verificar el proyecto seleccionado
        buscarTareasProyecto(proyecto);  // Buscar según el criterio ingresado
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        // TODO add your handling code here:
        cargarTareasEnTabla();
    }//GEN-LAST:event_btnTodosActionPerformed
    private void configurarTabla() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Nombre","Responsable","Estado","Proyecto"});

        tblTareas.setModel(model);  // Establecer el modelo en la tabla
    }
    
    
    private void buscarTareasProyecto(String proyecto) {
        DefaultTableModel model = (DefaultTableModel) tblTareas.getModel();
        model.setRowCount(0);  // Limpiar la tabla antes de cargar los resultados

        try {
            List<Invitado> tareas = tareaController.filtrarTareasporProyecto(proyecto);  // Si se ingresó Evento, buscar por Evento
             System.out.println("Cantidad de tareas encontradas por proyecto: " + tareas.size());

         
            for (Invitado tarea : tareas) {
                Object[] fila = {
                    tarea.getNombre(),
                    tarea.getResponsable(),
                    tarea.getEstado(),
                    tarea.getEvento(),
                   
                };
                model.addRow(fila);  // Agregar cada tarea como fila en la tabla
            }

            if (tareas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron tareas con los criterios proporcionados.", "Información", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (IOException e) {
           
            JOptionPane.showMessageDialog(this, "Error al buscar los libros.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    // Método para cargar los tareas en el JTable (carga inicial)
    private void cargarTareasEnTabla() {
        DefaultTableModel model = (DefaultTableModel) tblTareas.getModel();
        model.setRowCount(0);  // Limpiar la tabla antes de cargar

        try {
            
            List<Invitado> tareas = tareaController.listarTareas();  // Obtener todos los tareas desde el controlador
               System.out.println("Cantidad de tareas encontradas por proyecto: " + tareas.size());
               
            for (Invitado tarea : tareas) {
                Object[] fila = {
                    tarea.getNombre(),
                    tarea.getResponsable(),
                    tarea.getEstado(),
                    tarea.getEvento(),
                    
                };
                model.addRow(fila);  // Agregar cada tarea como fila en la tabla
            }

        } catch (IOException e) {
           
            JOptionPane.showMessageDialog(this, "Error al cargar las tareas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarAutoresEnComboBox() {
        try {
            List<Evento> autores = proyectoController.listarEventos();  // Obtener autores desde EventoController
            DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
            for (Evento autor : autores) {
                modelo.addElement(autor.getNombre());  // Agregar el nombre del proyecto al modelo del ComboBox
            }
            cboProyecto.setModel(modelo);  // Establecer el modelo en el JComboBox
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar autores.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscarTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnTodos;
    private javax.swing.JComboBox<String> cboProyecto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTareas;
    // End of variables declaration//GEN-END:variables
}
